site_name: Mosaic
version: 0.3.0
theme:
  name: material
  locale: en
  include_sidebar: true
  highlightjs: true
  logo: img/favicon-96x96.png
  custom_dir: custom_theme/
  titles_only: false
  navigation_depth: 2
  show_nav_level: 2
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
extra_css:
  - style.css
use_directory_urls: false
nav:
  - Introduction:
    - Introduction: index.md
    - Notation: notation.md
    - Technical Facts: facts.md
    - Status and Development: status.md
    - Principles of Design: principles.md
  - Mosaic Core:
    - Front Matter: front.md
    - Identity and Location:
      - Identity: identity.md
      - Bootstrap: bootstrap.md
      - URL: url.md
    - Data Formats:
      - Timestamps: timestamps.md
      - Kind: kind.md
      - Tags: tags.md
      - Record Format: record.md
      - Filter: filter.md
      - Human Readable Content: human_readable_content.md
      - References: reference.md
    - Protocol:
      - Network architecture: network.md
      - Protocol: protocol.md
      - Protocol messages: messages.md
      - Sync: sync.md
    - Transports:
      - Transports: transports.md
      - WebSockets: websockets.md
      - QUIC: quic.md
      - TCP with TLS: tcp.md
    - Accessory:
      - Human Encodings: human_encodings.md
      - Encrypted Secret Key: encrypted_secret_key.md
    - Core Application:
      - Key Schedule Record: keyschedule.md
      - Profile Record: profile.md
      - Core Tags: core_tags.md
      - Acquaintences and Friends: friends.md
      - Reporting: reporting.md
    - Appendices:
      - Cryptography: cryptography.md
      - Rationale: rationale.md
  - "App: Social Media":
    - Microblogging: microblog.md
    - Reply Comment: reply_comment.md
    - Blog: blog.md
    - Chat: chat.md
  - Registries:
    - Application Registry: applications.md
    - Record Kind Registry: kinds.md
    - Tag Type Registry: tag_types.md


